### ISSUE TITLE
As an unregistered User, when I press the Create Account button and verify my email, I will be taken into the application.

### ISSUE THREAD

**Issue by ezhao7** [ezhao7/cs2340_group16#21]
When the user presses the create account button,
If they are not already verified (code is already written to get verification),
then they will have the button on the left change to "Back to Login Screen", or have the screen disappear once email has been verified.

**Comment by bfaught3** [comment]
Tasks:
- 

Acceptance Scenarios:
- GIVEN an unregistered user is viewing the login page, WHEN the user presses the Create Account button, THEN the user is taken to the Create Account page.

- GIVEN an unregistered user is viewing the Create Account page, WHEN the user inputs an email, THEN an email containing a verification link is sent to the inputted email.

- GIVEN an unregistered user is viewing the verification email, WHEN the user opens the verification link, THEN the user is redirected to a confirmation page and the user's email is added to the database/the user is now registered.

- GIVEN a registered user is viewing the verification email, WHEN the user opens the verification link, THEN the user is redirected to a page claiming the link has been used or the verification request has expired.  

- GIVEN an unregistered user is viewing the Create Account page, WHEN the user inputs an email address that is not valid, THEN an email is not sent.

Done Done Criteria:
- User's email is added to the database and the user is now considered registered.
