### ISSUE TITLE
Dynamically Attach Clicklisteners to all elements in the ListView in ViewReportsActivity

### ISSUE THREAD

**Issue by tomonarifeehan** [ezhao7/cs2340_group16#61]
As we populate the ListView with reports, we should figure out how to attach a clicklistener to each entry and have each entry navigate to the ReportDetailsActivity and display the appropriate data for that specific report.

**Comment by tomonarifeehan** [comment]
Currently, there is an issue with the Intent in ViewWaterReportsActivity:

This line of code:
Intent newActivity1 = new Intent(ViewWaterSourcesActivity.this, ReportDetailsActivity.class);

Navigation from ViewWaterReportsActivity to ReportDetailsActivity is crashing.

**Comment by bfaught3** [comment]
Dealing with commented out switch statements apparently
toast is to be commented out

**Comment by tomonarifeehan** [comment]
lol... this is not done.

**Comment by tomonarifeehan** [comment]
Finally done.
