### ISSUE TITLE
Pull count from firebase and use it for report number.

### ISSUE THREAD

**Issue by ezhao7** [ezhao7/cs2340_group16#74]
Pull count from firebase and use for report number...
Pull it in viewreports and then show
Push it up in any activity that changes it.

**Comment by ezhao7** [comment]
Not needed?

**Comment by ezhao7** [comment]
@tomonarifeehan are we still doing this? if not let's close it

**Comment by tomonarifeehan** [comment]
@ezhao7 This is still needed if we want to display all reports in firebase (from multiple users). If we don't pull the count from firebase, we will have multiple "Report 1" and multiple "Report 2" when we display "All Reports"
