### ISSUE TITLE
[IMPORTANT] When changing email or password, change the actual Firebase Auth

### ISSUE THREAD

**Issue by ezhao7** [ezhao7/cs2340_group16#85]
Right now when changing the email or password, it changes how it is 
stored in the database.

Need to change this so that Firebase Authentication reflects these changes
as well.

**Comment by tomonarifeehan** [comment]
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#updatePassword(java.lang.String)

Apparently Firebase has updatePassword() method.

I think it will be easier if we prevent the user from editing their email but allow editing of password.
